# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from dji_er_tasks import combine_mission_layers as combine_mission_layers
from dji_er_tasks import count_aircraft as count_aircraft
from dji_er_tasks import count_failed as count_failed
from dji_er_tasks import count_ingested as count_ingested
from dji_er_tasks import count_located as count_located
from dji_er_tasks import count_photo_failed as count_photo_failed
from dji_er_tasks import count_photo_skipped as count_photo_skipped
from dji_er_tasks import count_posted as count_posted
from dji_er_tasks import count_skipped as count_skipped
from dji_er_tasks import extract_drone_gdf as extract_drone_gdf
from dji_er_tasks import extract_flight_results_df as extract_flight_results_df
from dji_er_tasks import extract_photo_results_df as extract_photo_results_df
from dji_er_tasks import extract_sightline_gdf as extract_sightline_gdf
from dji_er_tasks import extract_targets_gdf as extract_targets_gdf
from dji_er_tasks import extract_track_gdf as extract_track_gdf
from dji_er_tasks import format_total_distance as format_total_distance
from dji_er_tasks import format_total_flight_time as format_total_flight_time
from dji_er_tasks import ingest_mission as ingest_mission
from dji_er_tasks import set_aircraft_identity as set_aircraft_identity
from dji_er_tasks import set_decimation_rate as set_decimation_rate
from dji_er_tasks import set_dem_path as set_dem_path
from dji_er_tasks import set_dji_api_key as set_dji_api_key
from dji_er_tasks import set_event_type_name as set_event_type_name
from dji_er_tasks import set_imagery_event_type as set_imagery_event_type
from dji_er_tasks import set_input_folder as set_input_folder
from dji_er_tasks import set_operational_defaults as set_operational_defaults
from dji_er_tasks import set_patrol_type as set_patrol_type
from dji_er_tasks import set_photos_folder as set_photos_folder
from dji_er_tasks import set_time_defaults as set_time_defaults
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    dji_api_key = (
        task(set_dji_api_key)
        .validate()
        .set_task_instance_id("dji_api_key")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("dji_api_key") or {}))
        .call()
    )

    input_folder = (
        task(set_input_folder)
        .validate()
        .set_task_instance_id("input_folder")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("input_folder") or {}))
        .call()
    )

    event_type_name = (
        task(set_event_type_name)
        .validate()
        .set_task_instance_id("event_type_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("event_type_name") or {}))
        .call()
    )

    aircraft_identity = (
        task(set_aircraft_identity)
        .validate()
        .set_task_instance_id("aircraft_identity")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("aircraft_identity") or {}))
        .call()
    )

    decimation_rate = (
        task(set_decimation_rate)
        .validate()
        .set_task_instance_id("decimation_rate")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("decimation_rate") or {}))
        .call()
    )

    operational_defaults = (
        task(set_operational_defaults)
        .validate()
        .set_task_instance_id("operational_defaults")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("operational_defaults") or {}))
        .call()
    )

    photos_folder = (
        task(set_photos_folder)
        .validate()
        .set_task_instance_id("photos_folder")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("photos_folder") or {}))
        .call()
    )

    imagery_event_type = (
        task(set_imagery_event_type)
        .validate()
        .set_task_instance_id("imagery_event_type")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("imagery_event_type") or {}))
        .call()
    )

    dem_path = (
        task(set_dem_path)
        .validate()
        .set_task_instance_id("dem_path")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("dem_path") or {}))
        .call()
    )

    time_defaults = (
        task(set_time_defaults)
        .validate()
        .set_task_instance_id("time_defaults")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("time_defaults") or {}))
        .call()
    )

    patrol_type = (
        task(set_patrol_type)
        .validate()
        .set_task_instance_id("patrol_type")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("patrol_type") or {}))
        .call()
    )

    mission_result = (
        task(ingest_mission)
        .validate()
        .set_task_instance_id("mission_result")
        .handle_errors()
        .with_tracing()
        .partial(
            client=er_client_name,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            input_folder=input_folder,
            photos_folder=photos_folder,
            dji_api_key=dji_api_key,
            event_type_name=event_type_name,
            imagery_event_type=imagery_event_type,
            aircraft_identity=aircraft_identity,
            decimation_rate=decimation_rate,
            operational_defaults=operational_defaults,
            dem_path=dem_path,
            patrol_type=patrol_type,
            utc_offset_hours=time_defaults,
            **(params.get("mission_result") or {}),
        )
        .call()
    )

    track_gdf = (
        task(extract_track_gdf)
        .validate()
        .set_task_instance_id("track_gdf")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("track_gdf") or {}))
        .call()
    )

    targets_gdf = (
        task(extract_targets_gdf)
        .validate()
        .set_task_instance_id("targets_gdf")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("targets_gdf") or {}))
        .call()
    )

    drone_gdf = (
        task(extract_drone_gdf)
        .validate()
        .set_task_instance_id("drone_gdf")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("drone_gdf") or {}))
        .call()
    )

    sightline_gdf = (
        task(extract_sightline_gdf)
        .validate()
        .set_task_instance_id("sightline_gdf")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("sightline_gdf") or {}))
        .call()
    )

    flight_results_df = (
        task(extract_flight_results_df)
        .validate()
        .set_task_instance_id("flight_results_df")
        .handle_errors()
        .with_tracing()
        .partial(
            mission_result=mission_result, **(params.get("flight_results_df") or {})
        )
        .call()
    )

    photo_results_df = (
        task(extract_photo_results_df)
        .validate()
        .set_task_instance_id("photo_results_df")
        .handle_errors()
        .with_tracing()
        .partial(
            mission_result=mission_result, **(params.get("photo_results_df") or {})
        )
        .call()
    )

    track_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("track_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=track_gdf,
            tooltip_columns=["aircraft_serial", "takeoff_utc", "flight_time_min"],
            legend=None,
            layer_style={
                "color_column": "track_color",
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
            },
            **(params.get("track_layer") or {}),
        )
        .call()
    )

    sightline_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("sightline_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=sightline_gdf,
            tooltip_columns=["Photo", "Distance (m)"],
            legend={"labels": ["Line of sight"], "colors": ["#ffffff"]},
            layer_style={"get_color": "#ffffff", "get_width": 2, "opacity": 0.6},
            **(params.get("sightline_layer") or {}),
        )
        .call()
    )

    drone_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("drone_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=drone_gdf,
            tooltip_columns=[
                "Photo",
                "Time (UTC)",
                "Aircraft",
                "Height above takeoff (m)",
                "Camera heading (deg)",
                "Camera tilt (deg)",
            ],
            legend={
                "labels": ["Drone — where the photo was taken from"],
                "colors": ["#377eb8"],
            },
            layer_style={
                "get_radius": 5,
                "radius_units": "pixels",
                "get_fill_color": "#377eb8",
            },
            **(params.get("drone_layer") or {}),
        )
        .call()
    )

    target_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("target_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=targets_gdf,
            tooltip_columns=[
                "Photo",
                "Time (UTC)",
                "Distance from drone (m)",
                "Ground elevation (m)",
            ],
            legend={
                "labels": ["Target — where the camera was aimed"],
                "colors": ["#e41a1c"],
            },
            layer_style={
                "get_radius": 6,
                "radius_units": "pixels",
                "get_fill_color": "#e41a1c",
            },
            **(params.get("target_layer") or {}),
        )
        .call()
    )

    combined_layers = (
        task(combine_mission_layers)
        .validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            track_layer=track_layer,
            sightline_layer=sightline_layer,
            drone_layer=drone_layer,
            target_layer=target_layer,
            **(params.get("combined_layers") or {}),
        )
        .call()
    )

    mission_map = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("mission_map")
        .handle_errors()
        .with_tracing()
        .partial(
            title=None,
            tile_layers=[
                {
                    "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1.0,
                    "max_zoom": 20,
                    "min_zoom": 0,
                }
            ],
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right"},
            static=False,
            max_zoom=20,
            geo_layers=combined_layers,
            **(params.get("mission_map") or {}),
        )
        .call()
    )

    mission_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("mission_map_url")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="mission_map",
            text=mission_map,
            **(params.get("mission_map_url") or {}),
        )
        .call()
    )

    flight_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("flight_table_html")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=flight_results_df,
            widget_id="Flight Status",
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            columns=[
                "file",
                "aircraft_serial",
                "takeoff_utc",
                "flight_time_min",
                "battery_pct_takeoff",
                "battery_pct_landing",
                "battery_serial",
                "max_alt_agl_m",
                "max_speed_ms",
                "max_dist_m",
                "total_distance_m",
                "firmware",
                "status",
                "patrol",
                "error",
            ],
            **(params.get("flight_table_html") or {}),
        )
        .call()
    )

    flight_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("flight_table_url")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="flight_status",
            text=flight_table_html,
            **(params.get("flight_table_url") or {}),
        )
        .call()
    )

    photo_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("photo_table_html")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=photo_results_df,
            widget_id="Photo Status",
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            columns=[
                "file",
                "time_utc",
                "status",
                "target_lat",
                "target_lon",
                "slant_range_m",
                "camera_alt_m",
                "patrol",
                "error",
            ],
            **(params.get("photo_table_html") or {}),
        )
        .call()
    )

    photo_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("photo_table_url")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="photo_status",
            text=photo_table_html,
            **(params.get("photo_table_url") or {}),
        )
        .call()
    )

    stat_ingested = (
        task(count_ingested)
        .validate()
        .set_task_instance_id("stat_ingested")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_ingested") or {}))
        .call()
    )

    stat_skipped = (
        task(count_skipped)
        .validate()
        .set_task_instance_id("stat_skipped")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_skipped") or {}))
        .call()
    )

    stat_failed = (
        task(count_failed)
        .validate()
        .set_task_instance_id("stat_failed")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_failed") or {}))
        .call()
    )

    stat_flight_time = (
        task(format_total_flight_time)
        .validate()
        .set_task_instance_id("stat_flight_time")
        .handle_errors()
        .with_tracing()
        .partial(
            mission_result=mission_result, **(params.get("stat_flight_time") or {})
        )
        .call()
    )

    stat_distance = (
        task(format_total_distance)
        .validate()
        .set_task_instance_id("stat_distance")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_distance") or {}))
        .call()
    )

    stat_aircraft = (
        task(count_aircraft)
        .validate()
        .set_task_instance_id("stat_aircraft")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_aircraft") or {}))
        .call()
    )

    stat_posted = (
        task(count_posted)
        .validate()
        .set_task_instance_id("stat_posted")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_posted") or {}))
        .call()
    )

    stat_located = (
        task(count_located)
        .validate()
        .set_task_instance_id("stat_located")
        .handle_errors()
        .with_tracing()
        .partial(mission_result=mission_result, **(params.get("stat_located") or {}))
        .call()
    )

    stat_photo_skipped = (
        task(count_photo_skipped)
        .validate()
        .set_task_instance_id("stat_photo_skipped")
        .handle_errors()
        .with_tracing()
        .partial(
            mission_result=mission_result, **(params.get("stat_photo_skipped") or {})
        )
        .call()
    )

    stat_photo_failed = (
        task(count_photo_failed)
        .validate()
        .set_task_instance_id("stat_photo_failed")
        .handle_errors()
        .with_tracing()
        .partial(
            mission_result=mission_result, **(params.get("stat_photo_failed") or {})
        )
        .call()
    )

    widget_ingested = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_ingested")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Ingested",
            data=stat_ingested,
            decimal_places=0,
            **(params.get("widget_ingested") or {}),
        )
        .call()
    )

    widget_skipped = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_skipped")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Skipped",
            data=stat_skipped,
            decimal_places=0,
            **(params.get("widget_skipped") or {}),
        )
        .call()
    )

    widget_failed = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_failed")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Failed",
            data=stat_failed,
            decimal_places=0,
            **(params.get("widget_failed") or {}),
        )
        .call()
    )

    widget_flight_time = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_flight_time")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Flown",
            data=stat_flight_time,
            **(params.get("widget_flight_time") or {}),
        )
        .call()
    )

    widget_distance = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_distance")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Distance",
            data=stat_distance,
            **(params.get("widget_distance") or {}),
        )
        .call()
    )

    widget_aircraft = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_aircraft")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Aircraft",
            data=stat_aircraft,
            decimal_places=0,
            **(params.get("widget_aircraft") or {}),
        )
        .call()
    )

    widget_posted = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_posted")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Posted",
            data=stat_posted,
            decimal_places=0,
            **(params.get("widget_posted") or {}),
        )
        .call()
    )

    widget_located = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_located")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Located",
            data=stat_located,
            decimal_places=0,
            **(params.get("widget_located") or {}),
        )
        .call()
    )

    widget_photo_skipped = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_photo_skipped")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Duplicate",
            data=stat_photo_skipped,
            decimal_places=0,
            **(params.get("widget_photo_skipped") or {}),
        )
        .call()
    )

    widget_photo_failed = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_photo_failed")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Rejected",
            data=stat_photo_failed,
            decimal_places=0,
            **(params.get("widget_photo_failed") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mission Map",
            data=mission_map_url,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    flight_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("flight_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Flight Status",
            data=flight_table_url,
            **(params.get("flight_table_widget") or {}),
        )
        .call()
    )

    photo_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("photo_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Photo Status",
            data=photo_table_url,
            **(params.get("photo_table_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            time_range=None,
            details=workflow_details,
            widgets=[
                widget_ingested,
                widget_skipped,
                widget_failed,
                widget_flight_time,
                widget_distance,
                widget_aircraft,
                widget_posted,
                widget_located,
                widget_photo_skipped,
                widget_photo_failed,
                map_widget,
                flight_table_widget,
                photo_table_widget,
            ],
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
